### ISSUE TITLE
gnome-remote-desktop changes required for GNOME 42

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-control-center#10]
This commit dropped a few days ago - https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/58add5197e

What I think this means is that gnome-remote-desktop will not be started/function any more via BCC
That will need to be confirmed.

In the GNOME 42 version of Settings, gnome-remote-desktop changes from VNC to RDP - which I think is covered by this commit https://gitlab.gnome.org/GNOME/gnome-control-center/-/commit/0ae59467fbd694d59fa367a0621de2482f169f44

Ubuntu 22.04 is going to backport the changes (with obvious libadwaita changes removed) back into its GNOME 41 version of Settings that it is going to carry.

So - we should at the very least watch out of this - backport the changes ourselves/merge from Ubuntu to ensure Sharing remains as a capability in BCC

**Comment by Hi-Phile** [comment]
FWIW, I had a problem once the Budgie 10.6 DE was updated.  I ran into an issue where the Budgie task bar wouldn't open the 'Settings' when clicking on the 'Sound', Bluetooth settings, nor the Time/Date.  I had to manually replace the gnome-control-center with the budgie-control-center.

`sudo pacman -Rdd gnome-control-center`
then:
`yay -S budgie-control-center`

**Comment by fossfreedom** [comment]
Patching starting from commit https://github.com/BuddiesOfBudgie/budgie-control-center/commit/11323d9e4f8644f123d8f7dacedc0301e509adae
