### ISSUE TITLE
Problem with the sound card

### ISSUE THREAD

**Issue by AlexanderZhirov** [BuddiesOfBudgie/budgie-control-center#17]
After coming out of sleep mode, **Line Out** disappears and the sound is automatically connected via the front ports. The problem can be solved only by twitching the plug at the line output.
I noticed that after the update, the microphone basically fell off. Doesn't react to anything at all.
And the icons floated.

```
Linux Solus 4.3
Kernel 5.15.26-211.current
00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 05)
```

![изображение](https://user-images.githubusercontent.com/37277056/158696906-638bb13e-82bb-4e4e-b7dd-90091df54f85.png)

**Comment by fossfreedom** [comment]
> After coming out of sleep mode, Line Out disappears and the sound is automatically connected via the front ports.

That's not a budgie-control-center issue - likely to be a kernel/device issue.  Suggest raise with your distro.
