### ISSUE TITLE
libwacom is required?

### ISSUE THREAD

**Issue by Azania** [BuddiesOfBudgie/budgie-control-center#2]
During build I am crashing on needing libwacom despite not using any wacom hardware. I noticed that while gnome-control-center has this set as optional budgie-control-center doesn't. Maybe a check on the dependencies to see which ones are required would be best.

Maybe an idea of checking what optional build flags gnome-control-center has and take them over? I didn't check beyond libwacom atm myself.

**Comment by fossfreedom** [comment]
What distro are you building for?

**Comment by fossfreedom** [comment]
Note - I've checked gnome-control-center and wacom is not required for the s390 architecture - for all other architectures libwacom is needed.

https://gitlab.gnome.org/GNOME/gnome-control-center/-/blob/master/meson.build#L226

**Comment by Azania** [comment]
I am trying to build for gentoo.. As I am maintaining the budgie-desktop overlay for that distro I was tryiing to get the ebuild for budgie-control-center running. So I have been compairing and looking into the gnome-control-center.

Upon closer inspection it seems that Gentoo actually patches the meson.build. and meson_options.txt among other files. It seems that indeed normally it is required, It seems gentoo devs have complained about this to gnome itself as the ebuild (the file that tells how the package is build etc) states the following at the patches..

# Patches from gnome-40 branch on top of 40.0
# Makes some panels and dependencies optional
# https://bugzilla.gnome.org/686840, 697478, 700145
# Fix some absolute paths to be appropriate for Gentoo

The related bug reports tell the story I suppose.. The patches that Gentoo applies to gnome-control-center 41.2 can be found here: https://dev.gentoo.org/~mattst88/distfiles/gnome-control-center-41.2-patchset.tar.xz in which they made networkmanager, kerberos and wacom optional among other things (the gentoo specific stuff can be skipped obviously)

No wonder i ran into these issues as I wasn't expecting gentoo to actually patch and change build options. That is an oversight on my part but may still be interesting for the developers here.

As well there is a meson bug but you may have that fixed already (just noticed that 
(gentoo patch is https://dev.gentoo.org/~sam/distfiles/gnome-base/gnome-control-center/gnome-control-center-41.2-meson-0.61-build.patch.bz2 for meson 61+) I didn't check that yet here

**Comment by fossfreedom** [comment]
more than happy to see if we can make things easier to distro build for folks.  Happy to see any PRs here and we can discuss further.

**Comment by fossfreedom** [comment]
Closing - PR's can be used to support Gentoo's optional build requirements
