### ISSUE TITLE
Missing speaker icons in speaker test dialog

### ISSUE THREAD

**Issue by baraclese** [BuddiesOfBudgie/budgie-control-center#23]
## Description
Speaker icons are missing

## Budgie version
10.6

## Operating system
Arch Linux

## Actual result
![Screenshot from 2022-03-20 14-58-37](https://user-images.githubusercontent.com/1628879/159166193-b48e5292-3070-4f10-86cc-d136660cd3cb.png)

**Comment by fossfreedom** [comment]
Can confirm - not sure why the icons aren't being compiled into the sound gresource file though.  Needs investigating

https://github.com/BuddiesOfBudgie/budgie-control-center/blob/master/panels/sound/sound.gresource.xml

**Comment by fossfreedom** [comment]
@baraclese I believe the above commit solves this issue - please do test and let me know on your setup. thx

**Comment by baraclese** [comment]
@fossfreedom yes it works now.
