### ISSUE TITLE
Untranslated strings in the Budgie Control Center (French language)

### ISSUE THREAD

**Issue by roxfr** [BuddiesOfBudgie/budgie-control-center#26]
Budgie Version : 10.6.1
OS : Ubuntu 22.04 LTS 
Display server : X11

Hello,
There are untranslated strings (French language) in the Budgie Control Center.
See attached images.
Regards,
Roxfr

![Budgie_Control_Center_-_Displays_01](https://user-images.githubusercontent.com/52124613/170833651-9726bccb-fbdd-464e-a5f6-735af8bb5b9e.jpg)
![Budgie_Control_Center_-_Layout_01](https://user-images.githubusercontent.com/52124613/170833655-f0b09ec9-2867-419c-8ad6-1e051185f6f9.jpg)
![Budgie_Control_Center_-_Universal_access_01](https://user-images.githubusercontent.com/52124613/170833659-4f8e273d-85a9-4615-895e-87d6037e7d82.jpg)
![Budgie_Control_Center_-_Mouse Keyboard_01](https://user-images.githubusercontent.com/52124613/170840073-de22c96a-0494-40f7-8c1e-6a0caa0c8604.jpg)

**Comment by fossfreedom** [comment]
thx. Yeah - we'll need to connect BCC with buddiesofbudgie transifex.

**Comment by fossfreedom** [comment]
budgie-control-center is now translatable via transifex https://www.transifex.com/buddiesofbudgie/budgie-control-center
