### ISSUE TITLE
Missing navigation shorcuts setting

### ISSUE THREAD

**Issue by u2615** [BuddiesOfBudgie/budgie-control-center#3]
## Budgie version

- Budgie Control Center v0.3.0
- community/budgie-desktop 10.5.3-2
- community/budgie-desktop-view 1.1.1-1
- community/budgie-extras 1.3.0-1
- community/budgie-screensaver 4.0-2

## Operating system

EndeavoursOS Budgie

## Steps to reproduce the issue

- Build & install budgie-control-center
- try to set up navigation shortcuts (hide windows, move windows etc...)
- Entry isn't displayed  

## Actual result

![With budgie-control-center](https://user-images.githubusercontent.com/19215490/152140096-0a8720a7-a85f-495f-8172-8bc68e2b9a0b.png)

## Expected result
![With gnome-control-center](https://user-images.githubusercontent.com/19215490/152139968-a41a7aa8-dc12-4d15-9962-5db1855ef1aa.png)

**Comment by fossfreedom** [comment]
Can confirm that both Navigation and Windows are missing.

As to why ... not really sure. Needs digging into the code - somewhere in panels/keyboard in the source-code.

**Comment by fossfreedom** [comment]
ok - the above commit should fix this.

We do have an opportunity here to remove all the keyboard shortcuts that are not applicable to budgie.

So I would appreciate help here - to check each keybinding listed in each keyboard shortcuts to see if they work in budgie.  If they don't we should hide them from budgie-control-center.
