### ISSUE TITLE
Fails to build with gnome-desktop 43

### ISSUE THREAD

**Issue by jbicha** [BuddiesOfBudgie/budgie-control-center#31]
## Description
budgie-control-center fails to build with gnome-desktop 43 Alpha

## Budgie version
budgie-control-center 1.0.2-2 on Debian/Ubuntu

## Actual result
```
../panels/background/cc-background-chooser.c: In function ‘on_file_chooser_selection_changed_cb’:
../panels/background/cc-background-chooser.c:266:20: error: too few arguments to function ‘gnome_desktop_thumbnail_factory_generate_thumbnail’
  266 |           pixbuf = gnome_desktop_thumbnail_factory_generate_thumbnail (thumbnail_factory,
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../panels/background/cc-background-chooser.c:25:
/usr/include/gnome-desktop-3.0/libgnome-desktop/gnome-desktop-thumbnail.h:84:13: note: declared here
   84 | GdkPixbuf * gnome_desktop_thumbnail_factory_generate_thumbnail (GnomeDesktopThumbnailFactory *factory,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Additional information

gnome-desktop 43 Alpha is available in Debian experimental

It's possible to update the code so that it builds against the old gnome-desktop API and the new one. Here's an [example from cheese](https://gitlab.gnome.org/GNOME/cheese/-/commit/d58071c56d)

gnome-control-center 42 has a rewritten Background page which uses the gnome-desktop thumbnailer API differently and therefore wasn't affected by this issue

**Comment by fossfreedom** [comment]
corresponding debian bug report - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016175

**Comment by jbicha** [comment]
Thank you!!
