### ISSUE TITLE
Help is missing

### ISSUE THREAD

**Issue by Yannnd** [BuddiesOfBudgie/budgie-control-center#34]
## Description
Help functionality is absent, search returns nothing.

## Budgie version
10.6.2
Theme: "Plata-Compact"

## Operating system
Solus 4.3 Fortitude

## Steps to reproduce the issue
- Open Budgie Control Center by right clicking on the desktop and selecting "System Settings"
- Click on the three vertical dots right from the text "Budgie Control Center"
- Choose "Help"

## Actual result
An empty window appears, with normal title bar showing "Help", a favourites star icon, looking glass icon, three vertical dots icon.
Clicking the looking glass results in a search field opening. Entering relevant terms like "screen" or "volume" or whatever doesn't return anything at all, window stays empty.

## Expected result
Some info related to the entered search term or a menu to navigate in the help info?

**Comment by fossfreedom** [comment]
@EbonJaeger re this issue - on Ubuntu I see this process being run

    yelp help:gnome-help

On Ubuntu I see this type of screen and the help is searchable.

![image](https://user-images.githubusercontent.com/996240/184556335-facf9de8-c8e9-4904-8254-565e98054d7d.png)

So this is probably a packaging issue on Solus??

**Comment by serebit** [comment]
On Arch, this requires manual installation of `yelp` for the window to appear, and `gnome-user-docs` for the actual documentation to appear. Could be a Solus packaging issue, yeah.

**Comment by JoshStrobl** [comment]
Yea this is likely a Solus packaging issue. Yelp / Yelp-related docs weren't typically enabled.

**Comment by fossfreedom** [comment]
ok - closing this since this is specific to your distro @Yannnd .  Please raise on its https://dev.getsol.us/
