### ISSUE TITLE
Empty translation string for printer authentication-dialog.ui

### ISSUE THREAD

**Issue by GZGavinZhao** [BuddiesOfBudgie/budgie-control-center#35]
Is this intended? It's just a space?

Corresponding line in `budgie-control-center.pot`: https://github.com/BuddiesOfBudgie/budgie-control-center/blob/1b9fe8ee57feb6b46a2b0a879d107cc67177e44f/po/budgie-control-center.pot#L4160

**Comment by fossfreedom** [comment]
https://github.com/BuddiesOfBudgie/budgie-control-center/blob/1b9fe8ee57feb6b46a2b0a879d107cc67177e44f/panels/printers/authentication-dialog.ui#L11

Yeah. Thx for raising. The above doesn't make sense to have translatable=yes.


I will fix and mark that as no in a future update and will regenerate the pot. This will make the string disappear from transifex.

You can safely ignore that string for the moment.
