### ISSUE TITLE
lintian warnings about missing help files

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-control-center#49]
## Description
Building BCC under debian bookworm - lintian warning displayed
Running lintian...
W: budgie-control-center: no-manual-page [usr/libexec/budgie-cc-remote-login-helper]
W: budgie-control-center: no-manual-page [usr/libexec/budgie-control-center-print-renderer]

## Budgie version
v1.2.0

## Operating system
Debian Bookworm

## Steps to reproduce the issue
sbuild from source with lintian options

## Actual result
see description

## Expected result
No obvious lintian warnings

**Comment by serebit** [comment]
Why is this an issue? Binaries in libexec aren't user-facing and shouldn't need man pages.

**Comment by fossfreedom** [comment]
hmm - probably right - I'll raise a reportbug on debian and will report back

**Comment by fossfreedom** [comment]
Debian specific issue that is being  resolved
