### ISSUE TITLE
Changed position of displays in multi-monitor setup are not permanently

### ISSUE THREAD

**Issue by icunhacorrea** [BuddiesOfBudgie/budgie-control-center#50]
## Description

Hi! I have a setup with two monitors with my external on left side of laptop. So, how by default the monitors always be added on the right side, i need switch de positions of displays in control center. But, on switch, i notice that positions regularly rollback to the default positions in interval between 15 and 30 seconds.

## Budgie version
budgie-control-center 1.2.0.

## Operating system
Archlinux.

## Steps to reproduce the issue

1. Make a fresh install of Archlinux with budgie desktop.
2. Add a new monitor with a hdmi cable.
3. Switch the positions of display, putting the external monitor on left side.
4. Wait 15 ~ 30 seconds to the system rollback to default positions of display.

## Actual result
Positions of display altered by budgie-control-center don't be permanently.

## Expected result
Positions of display altered by budgie-control-center be permanently.

## Additional information
I tried switch the positions with arandr and works fine!

**Comment by JoshStrobl** [comment]
> Wait 15 ~ 30 seconds to the system rollback to default positions of display.

Yes because it provides a prompt that you need to accept otherwise it's unsure if it put your display in an incorrect configuration and needs to be reverted. This is no different than using GNOME Control Center.

**Comment by icunhacorrea** [comment]
Oh! It's true, however the prompt is not showing to keep the new settings. The same thing happens on my laptop here at home and on my workstation at work. Could I be forgetting something?

**Comment by fossfreedom** [comment]
hmm .... not sure.  The keep configuration dialog appears on ubuntu and debian itself.

Are you sure the dialog that appears hasn't just disappeared behind an open window? - use alt+tab to switch windows.

**Comment by icunhacorrea** [comment]
Yeah, I'm sure the dialog doesn't appear.

It is possible be a missing dependency of budgie-control-center package of archlinux?

I run the control center in verbose mode but no any errors appear.

The log in terminal show the configurations resetting.

```
13:28:34.0630          display-cc-panel:    DEBUG: Resetting current config!
(budgie-control-center:6653): dconf-DEBUG: 13:28:34.638: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6653): dconf-DEBUG: 13:28:34.701: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6653): dconf-DEBUG: 13:28:34.706: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6653): dconf-DEBUG: 13:28:34.707: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6653): dconf-DEBUG: 13:28:34.738: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6653): dconf-DEBUG: 13:28:34.738: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
13:28:44.0338          display-cc-panel:    DEBUG: setting adjustment -1.000 to -1:-0
13:28:44.0339          display-cc-panel:    DEBUG: setting adjustment -1.000 to -1:-0
13:28:54.0339          display-cc-panel:    DEBUG: setting adjustment -1.000 to -1:-0
13:28:54.0339          display-cc-panel:    DEBUG: setting adjustment -1.000 to -1:-0
13:28:54.0773          display-cc-panel:    DEBUG: Resetting current config!
```

**Comment by icunhacorrea** [comment]
Hi!

I figure out. It's a missing zenity dependency. After install zenity with `pacman -S zenity` the prompt to keep new display configurations normally appear.

I'll report a bug to budgie-control-center package of arch to requesting add the dependency.

Thank you.

**Comment by fossfreedom** [comment]
zenity is a dependency of budgie-desktop - the dialog you see is displayed by budgie-desktop/mutter.

I'll close this here - please do raise the dependency issue on budgie-desktop/arch.  cheers

**Comment by serebit** [comment]
Fixed on the Arch side.
