### ISSUE TITLE
Issue with multiple displays

### ISSUE THREAD

**Issue by cooperspencer** [BuddiesOfBudgie/budgie-control-center#51]
I try to move one display to the left in the settings but it keeps reverting it back to default. Also I don't get any confirmation dialogue at all.

```
../src/intel/isl/isl.c:2241: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
12:14:08.0699                      GLib:    DEBUG: setenv()/putenv() are not thread-safe and should not be used after threads are created
12:14:08.0707         cc-object-storage:    DEBUG: Finished creating D-Bus proxy for CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Color,/org/gnome/SettingsDaemon/Color,org.freedesktop.DBus.Properties)
12:14:08.0707         cc-object-storage:    DEBUG: Adding object GDBusProxy (CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Color,/org/gnome/SettingsDaemon/Color,org.freedesktop.DBus.Properties) → 0x7fbfa8024b50) to the storage
12:14:08.0707         cc-object-storage:    DEBUG: Finished creating D-Bus proxy for CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Color,/org/gnome/SettingsDaemon/Color,org.gnome.SettingsDaemon.Color)
12:14:08.0707         cc-object-storage:    DEBUG: Adding object GDBusProxy (CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Color,/org/gnome/SettingsDaemon/Color,org.gnome.SettingsDaemon.Color) → 0x7fbf9c0032e0) to the storage
12:14:08.0707          display-cc-panel:    DEBUG: setting adjustment -1.000 to -1:-0
12:14:08.0707          display-cc-panel:    DEBUG: setting adjustment -1.000 to -1:-0
12:14:08.0707         cc-object-storage:    DEBUG: Finished creating D-Bus proxy for CcObjectStorage::dbus-proxy(org.gnome.Shell,/org/gnome/Shell,org.gnome.Shell)
12:14:08.0707         cc-object-storage:    DEBUG: Adding object GDBusProxy (CcObjectStorage::dbus-proxy(org.gnome.Shell,/org/gnome/Shell,org.gnome.Shell) → 0x7fbf9c003050) to the storage
12:14:08.0707      diagnostics-cc-panel:    DEBUG: ABRT appeared
12:14:08.0716      thunderbolt-cc-panel:    DEBUG: Thunderbolt panel visible: yes
12:14:08.0716          display-cc-panel:    DEBUG: Resetting current config!
(budgie-control-center:6066): dconf-DEBUG: 12:14:08.718: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:08.718: watch_established: "/org/gnome/mutter/" (establishing: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:08.719: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:08.719: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:08.731: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:08.731: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:12.121: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:12.126: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
12:14:14.0219          display-cc-panel:    DEBUG: Resetting current config!
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.265: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.281: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.283: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.284: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.301: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.302: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
12:14:14.0328          display-cc-panel:    DEBUG: Resetting current config!
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.330: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.341: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.342: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.342: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.353: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.353: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
12:14:14.0353          display-cc-panel:    DEBUG: Resetting current config!
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.354: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.362: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.362: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.363: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.374: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.374: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
12:14:14.0777          display-cc-panel:    DEBUG: Resetting current config!
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.780: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.800: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.804: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.804: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.828: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.828: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
12:14:14.0828          display-cc-panel:    DEBUG: Resetting current config!
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.829: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.839: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.839: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.839: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.850: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
(budgie-control-center:6066): dconf-DEBUG: 12:14:14.850: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.414: change_fast
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.421: unwatch_fast: "/org/gnome/desktop/session/" (active: 1, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.430: unwatch_fast: "/org/gnome/mutter/" (active: 1, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.430: unwatch_fast: "/org/gnome/desktop/lockdown/" (active: 1, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.430: unwatch_fast: "/org/gnome/desktop/screensaver/" (active: 2, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.433: unwatch_fast: "/org/gnome/desktop/screensaver/" (active: 1, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.433: unwatch_fast: "/org/gnome/desktop/notifications/" (active: 1, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.433: unwatch_fast: "/org/gnome/settings-daemon/plugins/color/" (active: 1, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.433: unwatch_fast: "/org/gnome/desktop/interface/" (active: 1, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.435: unwatch_fast: "/org/buddiesofbudgie/control-center/" (active: 1, establishing: 0)
(budgie-control-center:6066): dconf-DEBUG: 12:14:17.435: sync
12:14:17.0436         cc-object-storage:    DEBUG: Destroying cached objects

```

**Comment by JoshStrobl** [comment]
@fossfreedom Any thoughts on this?

Here is a video posted by them on the issue: https://fosstodon.org/@buddyspencer/110021297381257319

Similar thing in GNOME Control Center: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2391

**Comment by fossfreedom** [comment]
isn't this the issue  that zenity wasn't packaged with budgie-desktop hence the dialog wouldn't appear?

**Comment by JoshStrobl** [comment]
zenity is packaged and is a dependency of budgie-desktop on Fedora.

**Comment by fossfreedom** [comment]
The confirmation dialog is from budgie-wm/mutter - no dialogs are initiated
by BCC.

**Comment by tp2kiss05** [comment]
> I try to move one display to the left in the settings but it keeps reverting it back to default. Also I don't get any confirmation dialogue at all.
> 
> ```
> ../src/intel/isl/isl.c:2241: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
> 12:14:08.0699                      GLib:    DEBUG: setenv()/putenv() are not thread-safe and should not be used after threads are created
> 12:14:08.0707         cc-object-storage:    DEBUG: Finished creating D-Bus proxy for CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Color,/org/gnome/SettingsDaemon/Color,org.freedesktop.DBus.Properties)
> 12:14:08.0707         cc-object-storage:    DEBUG: Adding object GDBusProxy (CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Color,/org/gnome/SettingsDaemon/Color,org.freedesktop.DBus.Properties) → 0x7fbfa8024b50) to the storage
> 12:14:08.0707         cc-object-storage:    DEBUG: Finished creating D-Bus proxy for CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Color,/org/gnome/SettingsDaemon/Color,org.gnome.SettingsDaemon.Color)
> 12:14:08.0707         cc-object-storage:    DEBUG: Adding object GDBusProxy (CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Color,/org/gnome/SettingsDaemon/Color,org.gnome.SettingsDaemon.Color) → 0x7fbf9c0032e0) to the storage
> 12:14:08.0707          display-cc-panel:    DEBUG: setting adjustment -1.000 to -1:-0
> 12:14:08.0707          display-cc-panel:    DEBUG: setting adjustment -1.000 to -1:-0
> 12:14:08.0707         cc-object-storage:    DEBUG: Finished creating D-Bus proxy for CcObjectStorage::dbus-proxy(org.gnome.Shell,/org/gnome/Shell,org.gnome.Shell)
> 12:14:08.0707         cc-object-storage:    DEBUG: Adding object GDBusProxy (CcObjectStorage::dbus-proxy(org.gnome.Shell,/org/gnome/Shell,org.gnome.Shell) → 0x7fbf9c003050) to the storage
> 12:14:08.0707      diagnostics-cc-panel:    DEBUG: ABRT appeared
> 12:14:08.0716      thunderbolt-cc-panel:    DEBUG: Thunderbolt panel visible: yes
> 12:14:08.0716          display-cc-panel:    DEBUG: Resetting current config!
> (budgie-control-center:6066): dconf-DEBUG: 12:14:08.718: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:08.718: watch_established: "/org/gnome/mutter/" (establishing: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:08.719: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:08.719: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:08.731: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:08.731: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:12.121: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:12.126: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> 12:14:14.0219          display-cc-panel:    DEBUG: Resetting current config!
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.265: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.281: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.283: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.284: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.301: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.302: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> 12:14:14.0328          display-cc-panel:    DEBUG: Resetting current config!
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.330: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.341: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.342: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.342: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.353: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.353: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> 12:14:14.0353          display-cc-panel:    DEBUG: Resetting current config!
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.354: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.362: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.362: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.363: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.374: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.374: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> 12:14:14.0777          display-cc-panel:    DEBUG: Resetting current config!
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.780: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.800: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.804: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.804: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.828: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.828: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> 12:14:14.0828          display-cc-panel:    DEBUG: Resetting current config!
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.829: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.839: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.839: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.839: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.850: watch_fast: "/org/gnome/mutter/" (establishing: 0, active: 1)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:14.850: unwatch_fast: "/org/gnome/mutter/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.414: change_fast
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.421: unwatch_fast: "/org/gnome/desktop/session/" (active: 1, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.430: unwatch_fast: "/org/gnome/mutter/" (active: 1, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.430: unwatch_fast: "/org/gnome/desktop/lockdown/" (active: 1, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.430: unwatch_fast: "/org/gnome/desktop/screensaver/" (active: 2, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.433: unwatch_fast: "/org/gnome/desktop/screensaver/" (active: 1, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.433: unwatch_fast: "/org/gnome/desktop/notifications/" (active: 1, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.433: unwatch_fast: "/org/gnome/settings-daemon/plugins/color/" (active: 1, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.433: unwatch_fast: "/org/gnome/desktop/interface/" (active: 1, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.435: unwatch_fast: "/org/buddiesofbudgie/control-center/" (active: 1, establishing: 0)
> (budgie-control-center:6066): dconf-DEBUG: 12:14:17.435: sync
> 12:14:17.0436         cc-object-storage:    DEBUG: Destroying cached objects
> ```

**Comment by fossfreedom** [comment]
Marking as a duplicate https://github.com/BuddiesOfBudgie/budgie-desktop/issues/356#issuecomment-1519120141
