### ISSUE TITLE
[Bug] Remote Desktop is disabled after each logout and login

### ISSUE THREAD

**Issue by dtrunk90** [BuddiesOfBudgie/budgie-control-center#55]
### Description

This is more likely a duplicate of https://gitlab.gnome.org/GNOME/gnome-remote-desktop/-/issues/93
Which was fixed with https://gitlab.gnome.org/GNOME/gnome-remote-desktop/-/merge_requests/92
But the issue persists in Fedora 38 Budgie (and probably other distributions as well).

### Budgie version

10.7.1

### Operating System

Fedora 38

### Steps to reproduce the issue

1. Go to Budgie Control Center
2. Click on Sharing
3. Enable Remote Desktop
4. Reboot
5. Now Remote Desktop is disabled again

### Actual result

Remote Desktop is disabled again after reboot

### Expected result

Remote Desktop should be enabled after reboot

**Comment by samlane-ma** [comment]
I was looking into this for our Raspberry Pi image for Ubuntu Budgie. I also noticed the merge request you linked did not fix the issue for us either. I am not sure what to offer as a "correct" fix, but my findings was that the service file can be further modified from their "fix":

`cp /usr/lib/systemd/user/gnome-remote-desktop.service ~/.config/systemd/user/`

edit ~/.config/systemd/user/gnome-remote-desktop.service

change:
`WantedBy=gnome-session.target`
to:
`WantedBy=default.target`

After making this change, it does stay enabled after logins. Again, I have only tried this on Ubuntu Budgie.

**Comment by dtrunk90** [comment]
> I was looking into this for our Raspberry Pi image for Ubuntu Budgie. I also noticed the merge request you linked did not fix the issue for us either. I am not sure what to offer as a "correct" fix, but my findings was that the service file can be further modified from their "fix":
> 
> `cp /usr/lib/systemd/user/gnome-remote-desktop.service ~/.config/systemd/user/`
> 
> edit ~/.config/systemd/user/gnome-remote-desktop.service
> 
> change: `WantedBy=gnome-session.target` to: `WantedBy=default.target`
> 
> After making this change, it does stay enabled after logins. Again, I have only tried this on Ubuntu Budgie.

I did the same as a workaround on Fedora. At least it works. Not sure if this can be considered a fix since budgie "calls gnome-session as part of the session startup". Might be a "race condition".

**Comment by fossfreedom** [comment]
Sharing is no longer an option in v1.4
