### ISSUE TITLE
Auto login doesn't work

### ISSUE THREAD

**Issue by dtrunk90** [BuddiesOfBudgie/budgie-control-center#56]
## Description

Tried to enable auto login in Budgie Control Center but after reboot it keeps asking for password. I've also noticed some weird toggle behavior like jumping back to disabled after trying to enable it.

I workaround it by manually creating a file `/etc/lightdm/lightdm.conf.d/autologin.conf` with the following content:
```
[Seat:*]
autologin-user=fedora
```

## Budgie version

budgie-desktop 10.7.1 / budgie-control-center 1.2.0

## Operating system

Fedora 38

## Steps to reproduce the issue

1. Go to Budgie Control Center
2. Click on User
3. Try to enable auto login

## Actual result

Auto login toggle jumps back to disabled state

## Expected result
Auto login can be enabled

**Comment by BlindRepublic** [comment]
This is due to SELinux. Running `setenforce 0` and tweaking the setting works.

**Comment by BlindRepublic** [comment]
Just to clarify, was this fixed upstream?

**Comment by fossfreedom** [comment]
Your distro needs to add some selinux rules for this to work.
