### ISSUE TITLE
Consider name change - either .desktop or window title

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-control-center#6]
## Description
The desktop file says "Budgie Control Center" https://github.com/BuddiesOfBudgie/budgie-control-center/blob/master/shell/budgie-control-center.desktop.in.in ... and the application title says "Settings".

We should be consistent.

Its arguable that "Settings" is too close to "Budgie Desktop Settings" - so maybe rename to "Budgie Control Center" ... or maybe something else?

## Budgie version
v0.3

## Operating system
N/A

## Steps to reproduce the issue
See the icon in the Menu and the title of the applicatoin

## Actual result
as above

## Expected result
Should be consistent

**Comment by JoshStrobl** [comment]
Yea I would just have the application title be "Budgie Control Center" :+1:
