### ISSUE TITLE
Lock Screen gets permanently deactivated whenever Budgie Control Center is opened

### ISSUE THREAD

**Issue by klamann** [BuddiesOfBudgie/budgie-control-center#81]
## Description

I have a pretty much fresh installation of Ubuntu Budgie 22.04. I noticed a couple of days after installing the OS that the lock screen stopped working. `Super + L` didn't do anything, `Lock` from the Power menu doesn't work and when I suspend the device, it is unlocked without having to enter a password after waking up. This is quite the security issue for me.

From what I can see, there is no way in Budgie Control Center to completely deactivate the lock screen functionality. Under "Displays" there is a setting for "Automatic Screen Lock", but on my system it is inactive and grayed out - I can't activate it.

So I tried to find a workaround for the problem and I can actually get the lock screen to work again with

    gsettings set org.gnome.desktop.lockdown disable-lock-screen false

But, when I start Budgie Control Center again, the setting immediately changes back

    # after launching budgie control center
    ❯ gsettings get org.gnome.desktop.lockdown disable-lock-screen
    true

This is terrible!

## Budgie version

budgie-control-center 1.0.1

## Operating system

Ubuntu Budgie 22.04.4

**Comment by fossfreedom** [comment]
Also - do check if you have fractional scaling enabled - if you do, the lock screen will not work.

**Comment by klamann** [comment]
> hmm - if you purge the package gjs (which will remove gnome-characters) does this fix things?

no change after removing this package



> Also - do check if you have fractional scaling enabled - if you do, the lock screen will not work.

what? I'm currently not using fractional scaling, but why would the lock screen stop working when I connect an external display that would require fractional scaling?

**Comment by fossfreedom** [comment]
It's a limitation of gnome-screensaver with fractional.

Are you still using slick-greeter or have you installer gdm3?  The latter
breaks budgie

**Comment by fossfreedom** [comment]
please post a screenshot of the displays tab in control-center.  Thx.

**Comment by klamann** [comment]
> Are you still using slick-greeter or have you installed gdm3? The latter breaks budgie.

slick-greeter, I guess, since gdm3 is not installed. I'm using the defaults that came with Ubuntu Budgie 22.04.

> please post a screenshot of the displays tab in control-center. Thx.

![image](https://github.com/BuddiesOfBudgie/budgie-control-center/assets/1008877/e302ad69-bff7-4cce-94e7-71d7bfd46a50)

turning off fractional scaling seems to resolve the issue.

![image](https://github.com/BuddiesOfBudgie/budgie-control-center/assets/1008877/6d72cd58-72bc-4882-bff7-3826618d4de4)

still, the UX feels terrible - there's no way for the user to know that fractional scaling and the lock screen are in any way related. And I would consider any function that deactivates the lock screen without notifying the user a security issue.

**Comment by fossfreedom** [comment]
"Fractional scaling will disable the lock-screen" - thats the wording shown in the screenshot when fractional scaling is being used.

**Comment by klamann** [comment]
well, I really like budgie, but this is a deal breaker for me. back to square one *sigh*

thanks for helping me to figure this out!

**Comment by serebit** [comment]
@klamann This is a limitation of [budgie-screensaver](https://github.com/BuddiesOfBudgie/budgie-screensaver). The lockscreen service that we'll be developing for the Wayland transition will not be subject to this limitation and should work just fine with fractional scaling. No ETA on that, though.
