### ISSUE TITLE
FTBFS against gcc-14

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-control-center#87]
## Description
Grrr ... debian has reported that budgie-control,center doesn't compile against gcc-14 ... currently in experimental but will make its way into testing soonish ... so needs fixing before it is drop kicked from the archive 

## Budgie version

1.4

## Operating system
Debian sid plus CC 14 compilation

## Steps to reproduce the issue

Bug#1074857: budgie-control-center: ftbfs with GCC-14

## Actual result
See linked bug report

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1074857

## Expected result
Compile against gcc14

**Comment by EbonJaeger** [comment]
This is fixed by #80.
